language: objective-c
before_install:
  - bundle install
xcode_workspace: iDroidLayout.xcworkspace
xcode_scheme: iDroidLayout
xcode_sdk: iphonesimulator8.1
cache:
  - bundler
  - cocoapods
install:
  - bundle exec pod install
script:
  - bundle exec xcodebuild -workspace iDroidLayout.xcworkspace -scheme iDroidLayout -sdk iphonesimulator8.1 build test | xcpretty -c
after_success:
  - bundle exec slather coverage iDroidLayout.xcodeproj
